### ISSUE TITLE
Attribute names with invalid characters (. and \)

### ISSUE THREAD

**Issue by sysprv** [jmesnil/jmx4r#1]
See for example attribute names under the amx:j2eeType=X-MonitoringDottedNames,name=na mbean of a GlassFish instance.

Trying to get the value of an attribute like server.http_service.file_cache.maxentries_lastsampletime doesn't work. &lt;&lt;MBean&gt;&gt;.method('server.http_service.file_cache.maxentries_lastsampletime').call returns a javax.management.Attribute, and calling getValue on that does the job.

Making MBean implement [] and working like a hash should do the job...

**Comment by jmesnil** [comment]
indeed, Ruby syntax will not allow a . in the attribute name.

Did you try to use the Object::send() method instead[1](http://ruby-doc.org/core/classes/Object.html#M000332):

server.send("http_service.file_cache.maxentries_lastsampletime")

I did not tested it but this should work.

**Comment by sysprv** [comment]
Yes, that should work too.
