### ISSUE TITLE
WebSphere Authentication 

### ISSUE THREAD

**Issue by rizzah** [jmesnil/jmx4r#3]
When passing the username and password it does not appear the gem is passing the username/password combination back to the JVM...

com/ibm/CORBA/iiop/UtilDelegateImpl.java:233:in `mapSystemException': javax.management.JMRuntimeException:  (NativeException)
        >> SERVER (id=19cc9094, host=localhost) TRACE START:
        >>    javax.management.JMRuntimeException: ADMN0022E: Access is denied for the getObjectNameStr operation on ORB MBean because of insufficient or empty credentials.

```
    from javax/rmi/CORBA/Util.java:84:in `mapSystemException'
    from org/omg/stub/javax/management/remote/rmi/_RMIConnection_Stub.java:523:in `getAttribute'
    from javax/management/remote/rmi/RMIConnector.java:886:in `getAttribute'
    from /usr/local/jruby/lib/ruby/gems/1.8/gems/jmx4r-0.1.3/lib/jmx4r.rb:36:in `method_missing'
    from /usr/local/jruby/lib/ruby/gems/1.8/gems/jmx4r-0.1.3/lib/jmx4r.rb:260:in `object_name'
```

**Comment by jmesnil** [comment]
do you have a test case which highlight the issue?

**Comment by rizzah** [comment]
http://publib.boulder.ibm.com/infocenter/wasinfo/v7r0/topic/com.ibm.websphere.base.doc/info/aes/ae/tjmx_develop_jsr160.html 

For IBM JDK's you need to include
-Dcom.ibm.CORBA.ConfigURL=file:
app_client_root/properties/sas.client.props
-Dcom.ibm.SSL.ConfigURL=file:
app_client_root/properties/ssl.client.props

As well as username/password.  You set these via
system.properties = java.lang.System.getProperties()
system.properties.setProperty("com.ibm.ssl.performURLHostNameVerification", "true")
system.properties.setProperty("com.ibm.SSL.ConfigURL", "file:ssl.client.props")
system.properties.setProperty("com.ibm.SSL.CORBA.ConfigURL", "file:sas.client.props")
system.properties.setProperty("java.naming.factory.initial", "com.ibm.websphere.name.WsnInitialContextFactory")

**Comment by jmesnil** [comment]
How did you set these properties in the Ruby client using jmx4r?

**Comment by rizzah** [comment]
I didn't thats the issue and thats why we are getting auth errors, just passing username/password for IBM's JDK with security enabled won't be enough.

**Comment by jmesnil** [comment]
I am not sure to understand if you solve your issue or not.
Did it work when you set these properties in the JVM used to run the JRuby client?

**Comment by rizzah** [comment]
Ive started working my own client webspheres mbeans aren't anything similar to "normal" java mbeans
