### ISSUE TITLE
jruby 1.7.0 deprecates include_class, already fixed but needs a gem release

### ISSUE THREAD

**Issue by atambo** [jmesnil/jmx4r#6]
Can we get a new gem release that includes this commit:

https://github.com/jmesnil/jmx4r/commit/4c78e0419797f648f6ebda3780883d08f23f0f1e

This will remove the spamming of deprecation warnings when using jruby 1.7.0.

**Comment by jmesnil** [comment]
I've pushed a new gem with this commit: https://rubygems.org/gems/jmx4r/versions/0.1.4

sorry, I forgot to release...

**Comment by atambo** [comment]
:heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart:
